/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#3b6a57",
        "on-tertiary-fixed": "#001e2c",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#002116",
        "error": "#ba1a1a",
        "surface-tint": "#5c5f61",
        "surface-bright": "#f9f9fa",
        "primary-fixed": "#e1e2e5",
        "on-surface": "#1a1c1d",
        "tertiary": "#000000",
        "on-primary-fixed": "#191c1e",
        "surface-dim": "#dadadb",
        "background": "#f9f9fa",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#68889c",
        "secondary-container": "#b6e8d1",
        "on-surface-variant": "#444749",
        "tertiary-fixed": "#c6e7fe",
        "surface": "#f9f9fa",
        "outline": "#75777a",
        "primary-fixed-dim": "#c5c7c9",
        "tertiary-container": "#001e2c",
        "secondary-fixed": "#bbedd6",
        "surface-container-high": "#e8e8e9",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#aacbe1",
        "on-primary": "#ffffff",
        "outline-variant": "#c4c7c9",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary-fixed-variant": "#204f3e",
        "on-tertiary-fixed-variant": "#2a4a5d",
        "surface-variant": "#e2e2e3",
        "surface-container-low": "#f3f3f4",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#444749",
        "surface-container": "#eeeeef",
        "secondary": "#396755",
        "inverse-primary": "#c5c7c9",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e2e2e3",
        "on-background": "#1a1c1d",
        "inverse-surface": "#2f3132",
        "primary": "#000000",
        "primary-container": "#191c1e",
        "on-primary-container": "#828486",
        "secondary-fixed-dim": "#a0d1bb",
        
        // Keep md- prefix for compatibility with existing code during transition
        md: {
          primary: "#000000",
          "on-primary": "#ffffff",
          "primary-container": "#191c1e",
          "on-primary-container": "#828486",
          secondary: "#396755",
          "on-secondary": "#ffffff",
          "secondary-container": "#b6e8d1",
          "on-secondary-container": "#3b6a57",
          tertiary: "#000000",
          "on-tertiary": "#ffffff",
          "tertiary-container": "#001e2c",
          "on-tertiary-container": "#68889c",
          error: "#ba1a1a",
          "on-error": "#ffffff",
          "error-container": "#ffdad6",
          "on-error-container": "#93000a",
          surface: "#f9f9fa",
          "surface-dim": "#dadadb",
          "surface-bright": "#f9f9fa",
          "surface-container-lowest": "#ffffff",
          "surface-container-low": "#f3f3f4",
          "surface-container": "#eeeeef",
          "surface-container-high": "#e8e8e9",
          "surface-container-highest": "#e2e2e3",
          "on-surface": "#1a1c1d",
          "on-surface-variant": "#444749",
          outline: "#75777a",
          "outline-variant": "#c4c7c9",
          background: "#f9f9fa",
          "on-background": "#1a1c1d",
        }
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        // FAB specific
        "fab": "1.75rem",
      },
      spacing: {
        "unit": "4px",
        "container-max": "1200px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-tablet": "24px"
      },
      fontFamily: {
        "title-lg": ["Inter"],
        "display-lg": ["Inter"],
        "title-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-lg": ["Inter"]
      },
      fontSize: {
        "title-lg": ["22px", {"lineHeight": "28px", "letterSpacing": "0px", "fontWeight": "500"}],
        "display-lg": ["57px", {"lineHeight": "64px", "letterSpacing": "-0.25px", "fontWeight": "400"}],
        "title-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0.15px", "fontWeight": "500"}],
        "label-sm": ["11px", {"lineHeight": "16px", "letterSpacing": "0.5px", "fontWeight": "500"}],
        "headline-md": ["28px", {"lineHeight": "36px", "letterSpacing": "0px", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0.5px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.25px", "fontWeight": "400"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1px", "fontWeight": "500"}]
      },
      boxShadow: {
        'md-1': '0 1px 3px 1px rgba(0,0,0,0.15), 0 1px 2px rgba(0,0,0,0.3)',
        'md-2': '0 2px 6px 2px rgba(0,0,0,0.15), 0 1px 2px rgba(0,0,0,0.3)',
        'md-3': '0 4px 8px 3px rgba(0,0,0,0.15), 0 1px 3px rgba(0,0,0,0.3)',
      },
    },
  },
  plugins: [],
};
